fix: skip `my-test-package.zip` file in `test_clone_contents`
  - With virtualenv version >= 20.13.0, the `test_clone_contents`
    started failing, because a zip file was present within the
    cloned virtualenv directory and couldn't be decoded as 'utf-8'.

  - Users saw the following error when running tests:

    ```
    File "virtualenv-clone/tests/test_virtualenv_clone.py", line 75, in test_clone_contents
        lines = f.read().decode('utf-8')
    UnicodeDecodeError: 'utf-8' codec can't decode byte 0xba in position 10: invalid start byte
    ```
  - The zip file, `my-test-package.zip`, is probably created because of
    the inclusion of the `my-test-package` with newer versions of setuptools.
    https://github.com/pypa/setuptools/issues/2709

  - This commit simply updates the test to skip over `.zip` files, like it
    already does for other types of binary files (`.pyc`, '.egg` etc.)